export const UPDATE_X_STAT = 'UPDATE_X_STAT';
export const UPDATE_Y_STAT = 'UPDATE_Y_STAT';
export const UPDATE_POSITION_FILTERS = 'UPDATE_POSITION_FILTERS';
export const UPDATE_TEAM_FILTERS = 'UPDATE_TEAM_FILTERS';
export const UPDATE_PLAYER_DATA = 'UPDATE_PLAYER_DATA';
